name: add_to_poem

on:
  schedule:
    - cron: "0 * * * *"    # run every hour on the hour, every day
  workflow_dispatch:       # allow running manually

jobs:
  add_to_poem:
    name : Add to Poem
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3 # checkout the repository content to github runner
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jinja2-humanize-extension
      - name: Run py script to update poem
        env:
          OPEN_WEATHER_API_KEY: ${{ secrets.OPEN_WEATHER_API_KEY }}
        run: python add_to_poem.py
        shell: sh
      - name: Push index.html changes back to repo
        uses: actions-js/push@v1.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
